### ISSUE TITLE
https://hub.docker.com/r/canfar/beacon/ returns error 404

### ISSUE THREAD

**Issue by xiuqin** [opencadc/vosui#1]
https://hub.docker.com/r/canfar/beacon/ 
returns error 404

**Comment by at88mph** [comment]
Hi there,

You created this in July, and I'm really sorry I missed it.  We're moving to the OpenCADC namespace, so the new link is http://hub.docker.com/r/opencadc/storage/.

Again, my apologies.

**Comment by at88mph** [comment]
Closing this as the link has changed.
